// Run with: tsx --tsconfig tsconfig.json scripts/generate-types.mts

import fs from 'node:fs/promises'
import path from 'node:path'
import { loadConfig, root } from './lib/bootstrap.mts'

const config = await loadConfig()

const { configToJSONSchema } = await import('payload')
const { initI18n } = await import('@payloadcms/translations')
const { compile } = await import('json-schema-to-typescript')

const i18n = await initI18n({ config: config.i18n, context: 'api', language: 'en' })
const jsonSchema = configToJSONSchema(config, config.db.defaultIDType, i18n)

const banner = [
  '/* tslint:disable */',
  '/* eslint-disable */',
  '/**',
  ' * This file was automatically generated by Payload.',
  ' * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,',
  " * and re-run `npm run generate:types` to regenerate this file.",
  ' */',
].join('\n')

const compiled = await compile(jsonSchema, 'Config', {
  bannerComment: banner,
  style: { singleQuote: true },
  unreachableDefinitions: true,
})

const declare = `declare module 'payload' {\n  export interface GeneratedTypes extends Config {}\n}`
const outputFile = path.join(root, 'src/payload-types.ts')
await fs.writeFile(outputFile, `${compiled}\n${declare}\n`)

console.log('✓ payload-types.ts written')
