// Import the "Where it works" per-SKU application-card pack into the site.
//
// Source pack (generated outside the repo — images + copy per SKU):
//   ~/Documents/New project/outputs/ENVO Product Subpage Where It Works/final-current-sku
// Pack logic/authoring rules live in that folder's LOGIC_AND_MEMORY.md.
//
// What it does:
//   1. reads sku-data-snippets.json (SKU-keyed cards: title, pick, image)
//   2. resizes every card image to 800px wide (cards render ~280px; 800 covers
//      2x retina) and writes it under public/assets/images/where-it-works/…
//   3. emits src/data/sku-where-it-works.generated.ts
//   4. validates: 4 cards per SKU, every image present, no empty copy
//
// Usage: npx tsx --tsconfig tsconfig.json scripts/import-where-it-works.mts [pack-dir]
import fs from 'node:fs'
import path from 'node:path'
import sharp from 'sharp'

const PACK_DIR =
  process.argv[2] ??
  path.join(
    process.env.HOME ?? '',
    'Documents/New project/outputs/ENVO Product Subpage Where It Works/final-current-sku',
  )
const REPO = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..')
const OUT_TS = path.join(REPO, 'src/data/sku-where-it-works.generated.ts')

type PackImage = { src: string; local: boolean; alt: string; cover?: boolean }
type PackCard = { title: string; pick: string; image: PackImage }
type PackEntry = {
  url: string
  sku: string
  series: string
  sectionEyebrow: string
  sectionTitle: string
  solutions: PackCard[]
}

const pack: Record<string, PackEntry> = JSON.parse(
  fs.readFileSync(path.join(PACK_DIR, 'sku-data-snippets.json'), 'utf8'),
)

const problems: string[] = []
const out: Record<string, { sectionTitle: string; solutions: { title: string; pick: string; image: { src: string; local: true; alt: string } }[] }> = {}

let copied = 0
for (const [key, entry] of Object.entries(pack)) {
  if (entry.solutions.length !== 4) problems.push(`${key}: ${entry.solutions.length} cards (want 4)`)
  if (!entry.sectionTitle?.trim()) problems.push(`${key}: empty sectionTitle`)

  const solutions = []
  for (const card of entry.solutions) {
    if (!card.title?.trim() || !card.pick?.trim()) problems.push(`${key}: empty card copy`)
    // pack src is site-absolute (/assets/images/where-it-works/current-sku/<family>/<SKU>/NN-*.jpg);
    // the source file sits in the pack at <family>/<SKU>/NN-*.jpg
    const rel = card.image.src.replace(/^\/assets\/images\/where-it-works\/current-sku\//, '')
    const srcFile = path.join(PACK_DIR, rel)
    const destFile = path.join(REPO, 'public', card.image.src)
    if (!fs.existsSync(srcFile)) {
      problems.push(`${key}: missing source image ${rel}`)
      continue
    }
    fs.mkdirSync(path.dirname(destFile), { recursive: true })
    await sharp(srcFile).resize({ width: 800 }).jpeg({ quality: 80, mozjpeg: true }).toFile(destFile)
    copied++
    solutions.push({ title: card.title, pick: card.pick, image: { src: card.image.src, local: true as const, alt: card.image.alt } })
  }
  out[entry.sku] = { sectionTitle: entry.sectionTitle, solutions }
}

if (problems.length) {
  console.error(`✗ ${problems.length} problems:\n` + problems.map((p) => `  - ${p}`).join('\n'))
  process.exit(1)
}

const header = `// AUTO-GENERATED by scripts/import-where-it-works.mts — DO NOT EDIT BY HAND.
// Per-SKU "Where it works" application cards (scene image + concrete copy).
// AI-draft imagery/copy pending Wei review; regenerate by re-running the script
// against a new pack export.

export type SkuWhereItWorks = {
  sectionTitle: string
  solutions: { title: string; pick: string; image: { src: string; local: true; alt: string } }[]
}

export const SKU_WHERE_IT_WORKS: Record<string, SkuWhereItWorks> = `

fs.writeFileSync(OUT_TS, header + JSON.stringify(out, null, 2) + '\n')
console.log(`✓ ${Object.keys(out).length} SKUs, ${copied} images resized → public/, data → ${path.relative(REPO, OUT_TS)}`)
