/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `npm run generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    media: Media;
    posts: Post;
    projects: Project;
    pages: Page;
    faqs: Faq;
    submissions: Submission;
    'lead-files': LeadFile;
    events: Event;
    'page-seo': PageSeo;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect;
    media: MediaSelect;
    posts: PostsSelect;
    projects: ProjectsSelect;
    pages: PagesSelect;
    faqs: FaqsSelect;
    submissions: SubmissionsSelect;
    'lead-files': LeadFilesSelect;
    events: EventsSelect;
    'page-seo': PageSeoSelect;
    users: UsersSelect;
    'payload-kv': PayloadKvSelect;
    'payload-locked-documents': PayloadLockedDocumentsSelect;
    'payload-preferences': PayloadPreferencesSelect;
    'payload-migrations': PayloadMigrationsSelect;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect;
    'home-page': HomePageSelect;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * ENVO product catalogue. Synced from Akeneo — edit freely. Enable sync_locked to prevent Akeneo from overwriting your changes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Synced from Akeneo. Edit freely.
   */
  name: string;
  /**
   * Short tagline shown under the product name.
   */
  subtitle?: string | null;
  /**
   * One-line summary used in search results and meta tags.
   */
  short_description?: string | null;
  /**
   * Full product description. Accepts HTML. Synced from Akeneo — edit to override.
   */
  description?: string | null;
  /**
   * Show on website.
   */
  enabled?: boolean | null;
  /**
   * Hide without disabling in Akeneo.
   */
  hidden?: boolean | null;
  /**
   * Primary product image. Upload to replace the Akeneo image.
   */
  image?: (number | null) | Media;
  /**
   * Clean product image on white background. Used for category cards.
   */
  clean_image?: (number | null) | Media;
  /**
   * Akeneo S3 image URL — used automatically if no image is uploaded above. Do not edit.
   */
  image_url_fallback?: string | null;
  /**
   * Akeneo S3 clean image URL — fallback if no clean image uploaded. Do not edit.
   */
  clean_image_url_fallback?: string | null;
  /**
   * Link to the spec sheet PDF. Can be an Akeneo URL or any external link.
   */
  spec_sheet_url?: string | null;
  power_w?: number | null;
  output_voltage_v?: number | null;
  input_voltage_min_v?: number | null;
  input_voltage_max_v?: number | null;
  rated_current_a?: number | null;
  number_of_outputs?: number | null;
  operation_mode?: ('cv' | 'cc' | 'cv_cc') | null;
  dimming_control?:
    | ('none' | 'dali' | '0_10v' | 'pwm' | 'triac' | 'casambi' | 'dmx' | 'knx' | 'matter' | 'zigbee')[]
    | null;
  cc_region_min?: number | null;
  cc_region_max?: number | null;
  /**
   * Raw array from Akeneo. e.g. ["push_dim","rf"]
   */
  controller_type?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * e.g. 1ch, rgb, rgbw, cct
   */
  output_channel?: string | null;
  /**
   * e.g. cv, cc, pwm
   */
  output_type?: string | null;
  module_size?: number | null;
  switch_no_module?: number | null;
  /**
   * e.g. push, touch, rotary
   */
  switch_operation_method?: string | null;
  /**
   * e.g. surface, recessed, din_rail, in_wall
   */
  mounting_info?: string | null;
  switch_back_light?: boolean | null;
  /**
   * e.g. white, black, silver
   */
  finish_colour?: string | null;
  /**
   * e.g. aluminum, plastic, steel
   */
  material?: string | null;
  brightness_lm?: number | null;
  efficacy_lm_w?: number | null;
  cct_k?: number | null;
  cri?: number | null;
  beam_angle_deg?: number | null;
  lifetime_hrs?: number | null;
  max_in_series?: number | null;
  led_chip_colour?: ('warm_white' | 'natural_white' | 'cool_white' | 'rgb' | 'rgbw' | 'tunable_white') | null;
  led_pitch?: number | null;
  /**
   * Raw array from Akeneo.
   */
  led_light_power_input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  length_mm?: number | null;
  width_mm?: number | null;
  height_mm?: number | null;
  weight_kg?: number | null;
  waterproof?: ('non_waterproof' | 'ip20' | 'ip44' | 'ip65' | 'ip67' | 'ip68') | null;
  temp_min_c?: number | null;
  temp_max_c?: number | null;
  sensor_type?: ('pir' | 'microwave' | 'daylight' | 'dual') | null;
  /**
   * e.g. pir, microwave, infrared
   */
  technology?: string | null;
  /**
   * e.g. 12m, 6m radius
   */
  maximum_detection_range?: string | null;
  multiway?: boolean | null;
  standards_met?:
    | (
        | 'c_ce'
        | 'c_tuv'
        | 'c_rohs'
        | 'c_saa'
        | 'c_ul'
        | 'c_cul'
        | 'c_cb'
        | 'c_bis'
        | 'c_rcm'
        | 'c_fcc'
        | 'c_selv'
        | 'c_enec'
        | 'c_lm80'
      )[]
    | null;
  warranty_years?: number | null;
  /**
   * Retail price ex-GST.
   */
  price_nzd?: number | null;
  inventory_type?: ('stocked' | 'on_demand') | null;
  /**
   * Units per carton.
   */
  pack_qty?: number | null;
  shipping_lead_days?: number | null;
  manufacturing_lead_days?: number | null;
  /**
   * Show in featured sections.
   */
  featured?: boolean | null;
  badge?: ('' | 'new' | 'popular' | 'sale' | 'clearance') | null;
  /**
   * Lower = appears first.
   */
  display_order?: number | null;
  /**
   * Short note on the product page. e.g. "Popular for commercial signage."
   */
  marketing_note?: string | null;
  /**
   * Which application pages feature this product.
   */
  applications?:
    | {
        /**
         * e.g. signage, cabinetry, residential, outdoor
         */
        application_slug: string;
        /**
         * Pin to top of this application page.
         */
        pinned?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Manually curated. Leave empty to auto-generate from same series.
   */
  related_skus?:
    | {
        /**
         * e.g. SC-60-24
         */
        sku: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Page title tag. Synced from Akeneo.
   */
  seo_title?: string | null;
  /**
   * Meta description. Synced from Akeneo.
   */
  seo_description?: string | null;
  /**
   * Questions and answers shown on the product page. Synced from Akeneo — edit freely.
   */
  faq?:
    | {
        question: string;
        answer: string;
        category?: ('Specs' | 'Application' | 'Compatibility' | 'Environment' | 'Comparison') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, Akeneo sync will skip this product entirely. Use when you have manually customised this product and do not want it overwritten.
   */
  sync_locked?: boolean | null;
  /**
   * Akeneo SKU — do not edit.
   */
  sku: string;
  family?: string | null;
  series?: string | null;
  brand?: string | null;
  /**
   * Akeneo category codes.
   */
  categories?:
    | {
        code?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Last time this product was updated from Akeneo.
   */
  akeneo_synced_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO. e.g. "SC-100-24 LED Driver front view"
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * ENVO editorial content. Publish to make a post visible on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Shown on blog cards and used as the meta-description fallback (max 200 characters).
   */
  excerpt: string;
  /**
   * Cover image — used on list cards and as the detail-page header.
   */
  cover: number | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. Falls back to the post title if empty.
   */
  seoTitle?: string | null;
  /**
   * Optional. Falls back to the excerpt if empty.
   */
  seoDescription?: string | null;
  /**
   * Optional. Falls back to the cover image if empty.
   */
  ogImage?: (number | null) | Media;
  /**
   * When the post goes live. Set a future date/time to schedule it.
   */
  publishedAt: string;
  /**
   * Primary section. Drives the /blog/category pages.
   */
  category: 'guides' | 'tech_insights' | 'company_news' | 'industry';
  /**
   * Show in featured spots on /blog and the home page.
   */
  featured?: boolean | null;
  /**
   * Post URL: /blog/<slug>. Auto-filled from the title — edit only for a custom URL.
   */
  slug: string;
  /**
   * Free-form tags. Power the /blog/tag pages.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Estimated minutes to read. Calculated on save.
   */
  readingTime?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Real-world ENVO LED installations. Publish to make a case study visible on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Client or building owner. Leave blank if under NDA.
   */
  client?: string | null;
  /**
   * City and country.
   */
  location?: string | null;
  /**
   * Year completed.
   */
  completedYear?: number | null;
  /**
   * Shown on project cards and used as the meta-description fallback (max 200 characters).
   */
  excerpt: string;
  /**
   * Cover image — used on list cards and as the detail-page hero.
   */
  cover: number | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Install photos. Caption is optional but boosts SEO + alt-text quality.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ENVO SKU codes used in this install. Front-end resolves each via getProduct() at render time — type a real Akeneo SKU.
   */
  productsUsed?:
    | {
        sku: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Headline stats shown on the featured card and the detail hero (e.g. 1,920 / Modules). Up to 4. Use real ENVO product params; leave empty to hide the spec row.
   */
  specs?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to hide the testimonial block.
   */
  testimonial?: string | null;
  /**
   * Optional. Falls back to the project title if empty.
   */
  seoTitle?: string | null;
  /**
   * Optional. Falls back to the excerpt if empty.
   */
  seoDescription?: string | null;
  /**
   * Optional. Falls back to the cover image if empty.
   */
  ogImage?: (number | null) | Media;
  /**
   * When the project goes live. Set a future date/time to schedule it.
   */
  publishedAt: string;
  /**
   * Drives /projects/industry/[i] pages. Pick all that fit — a project can span sectors.
   */
  industry: ('retail' | 'hotel' | 'storefront' | 'architectural' | 'canopy' | 'other')[];
  /**
   * Show in the Featured strip on /projects and the home page.
   */
  featured?: boolean | null;
  /**
   * Project URL: /projects/<slug>. Auto-filled from the title — edit only for a custom URL.
   */
  slug: string;
  /**
   * Free-form tags. Power the /projects/tag/[t] pages.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Standalone rich-text pages. Publish to make a page Visible on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * URL slug. Policy pages render at /<slug>; other pages at /pages/<slug>.
   */
  slug?: string | null;
  /**
   * Show this page in the footer legal links.
   */
  showInFooter?: boolean | null;
  /**
   * Optional. Falls back to the page title.
   */
  seoTitle?: string | null;
  /**
   * Meta description (aim ≤ 155 chars).
   */
  metaDescription?: string | null;
  /**
   * The "Last updated" date shown on the page. Set this manually; it does NOT auto-change on save.
   */
  lastUpdated?: string | null;
  /**
   * Optional social share image.
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Questions answered on /resources/faq. Publish to make one visible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Which FAQ section this appears under.
   */
  group: 'ordering' | 'products' | 'installation' | 'warranty';
  /**
   * Sort order within the group (low → high).
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Enquiries captured from the website. Newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  type: 'free-layout' | 'find-your-match' | 'contact';
  status?: ('new' | 'contacted' | 'archived') | null;
  name?: string | null;
  email?: string | null;
  company?: string | null;
  phone?: string | null;
  /**
   * Page the lead came from.
   */
  sourcePath?: string | null;
  /**
   * Uploaded sketch / drawing (Free Layout).
   */
  sketch?: (number | null) | LeadFile;
  /**
   * Raw form fields / wizard answers.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-files".
 */
export interface LeadFile {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  kind: 'pageview' | 'find-your-match';
  path?: string | null;
  referrer?: string | null;
  sessionHash?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SEO title / description / share image for code-built pages, keyed by route. Empty fields fall back to the page’s in-code defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-seo".
 */
export interface PageSeo {
  id: number;
  /**
   * Exact route path, e.g. /about or /solutions/signage-lighting
   */
  route: string;
  /**
   * Optional friendly name shown in the admin list.
   */
  label?: string | null;
  /**
   * Overrides the <title>. Leave blank to keep the page default.
   */
  seoTitle?: string | null;
  /**
   * Overrides <meta name="description">. Aim ≤ 155 characters.
   */
  metaDescription?: string | null;
  /**
   * Optional social share image.
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admins can manage users and settings. Editors can create and edit content.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'lead-files';
        value: number | LeadFile;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'page-seo';
        value: number | PageSeo;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect {
  name?: boolean;
  subtitle?: boolean;
  short_description?: boolean;
  description?: boolean;
  enabled?: boolean;
  hidden?: boolean;
  image?: boolean;
  clean_image?: boolean;
  image_url_fallback?: boolean;
  clean_image_url_fallback?: boolean;
  spec_sheet_url?: boolean;
  power_w?: boolean;
  output_voltage_v?: boolean;
  input_voltage_min_v?: boolean;
  input_voltage_max_v?: boolean;
  rated_current_a?: boolean;
  number_of_outputs?: boolean;
  operation_mode?: boolean;
  dimming_control?: boolean;
  cc_region_min?: boolean;
  cc_region_max?: boolean;
  controller_type?: boolean;
  output_channel?: boolean;
  output_type?: boolean;
  module_size?: boolean;
  switch_no_module?: boolean;
  switch_operation_method?: boolean;
  mounting_info?: boolean;
  switch_back_light?: boolean;
  finish_colour?: boolean;
  material?: boolean;
  brightness_lm?: boolean;
  efficacy_lm_w?: boolean;
  cct_k?: boolean;
  cri?: boolean;
  beam_angle_deg?: boolean;
  lifetime_hrs?: boolean;
  max_in_series?: boolean;
  led_chip_colour?: boolean;
  led_pitch?: boolean;
  led_light_power_input?: boolean;
  length_mm?: boolean;
  width_mm?: boolean;
  height_mm?: boolean;
  weight_kg?: boolean;
  waterproof?: boolean;
  temp_min_c?: boolean;
  temp_max_c?: boolean;
  sensor_type?: boolean;
  technology?: boolean;
  maximum_detection_range?: boolean;
  multiway?: boolean;
  standards_met?: boolean;
  warranty_years?: boolean;
  price_nzd?: boolean;
  inventory_type?: boolean;
  pack_qty?: boolean;
  shipping_lead_days?: boolean;
  manufacturing_lead_days?: boolean;
  featured?: boolean;
  badge?: boolean;
  display_order?: boolean;
  marketing_note?: boolean;
  applications?:
    | boolean
    | {
        application_slug?: boolean;
        pinned?: boolean;
        id?: boolean;
      };
  related_skus?:
    | boolean
    | {
        sku?: boolean;
        id?: boolean;
      };
  seo_title?: boolean;
  seo_description?: boolean;
  faq?:
    | boolean
    | {
        question?: boolean;
        answer?: boolean;
        category?: boolean;
        id?: boolean;
      };
  sync_locked?: boolean;
  sku?: boolean;
  family?: boolean;
  series?: boolean;
  brand?: boolean;
  categories?:
    | boolean
    | {
        code?: boolean;
        id?: boolean;
      };
  akeneo_synced_at?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect {
  alt?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  url?: boolean;
  thumbnailURL?: boolean;
  filename?: boolean;
  mimeType?: boolean;
  filesize?: boolean;
  width?: boolean;
  height?: boolean;
  focalX?: boolean;
  focalY?: boolean;
  sizes?:
    | boolean
    | {
        thumbnail?:
          | boolean
          | {
              url?: boolean;
              width?: boolean;
              height?: boolean;
              mimeType?: boolean;
              filesize?: boolean;
              filename?: boolean;
            };
        card?:
          | boolean
          | {
              url?: boolean;
              width?: boolean;
              height?: boolean;
              mimeType?: boolean;
              filesize?: boolean;
              filename?: boolean;
            };
        detail?:
          | boolean
          | {
              url?: boolean;
              width?: boolean;
              height?: boolean;
              mimeType?: boolean;
              filesize?: boolean;
              filename?: boolean;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect {
  title?: boolean;
  excerpt?: boolean;
  cover?: boolean;
  body?: boolean;
  seoTitle?: boolean;
  seoDescription?: boolean;
  ogImage?: boolean;
  publishedAt?: boolean;
  category?: boolean;
  featured?: boolean;
  slug?: boolean;
  tags?:
    | boolean
    | {
        tag?: boolean;
        id?: boolean;
      };
  readingTime?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  _status?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect {
  title?: boolean;
  client?: boolean;
  location?: boolean;
  completedYear?: boolean;
  excerpt?: boolean;
  cover?: boolean;
  body?: boolean;
  gallery?:
    | boolean
    | {
        image?: boolean;
        caption?: boolean;
        id?: boolean;
      };
  productsUsed?:
    | boolean
    | {
        sku?: boolean;
        id?: boolean;
      };
  specs?:
    | boolean
    | {
        value?: boolean;
        label?: boolean;
        id?: boolean;
      };
  testimonial?: boolean;
  seoTitle?: boolean;
  seoDescription?: boolean;
  ogImage?: boolean;
  publishedAt?: boolean;
  industry?: boolean;
  featured?: boolean;
  slug?: boolean;
  tags?:
    | boolean
    | {
        tag?: boolean;
        id?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  _status?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect {
  title?: boolean;
  content?: boolean;
  slug?: boolean;
  showInFooter?: boolean;
  seoTitle?: boolean;
  metaDescription?: boolean;
  lastUpdated?: boolean;
  ogImage?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  _status?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect {
  question?: boolean;
  answer?: boolean;
  group?: boolean;
  order?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  _status?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect {
  type?: boolean;
  status?: boolean;
  name?: boolean;
  email?: boolean;
  company?: boolean;
  phone?: boolean;
  sourcePath?: boolean;
  sketch?: boolean;
  data?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-files_select".
 */
export interface LeadFilesSelect {
  alt?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  url?: boolean;
  thumbnailURL?: boolean;
  filename?: boolean;
  mimeType?: boolean;
  filesize?: boolean;
  width?: boolean;
  height?: boolean;
  focalX?: boolean;
  focalY?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect {
  kind?: boolean;
  path?: boolean;
  referrer?: boolean;
  sessionHash?: boolean;
  data?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-seo_select".
 */
export interface PageSeoSelect {
  route?: boolean;
  label?: boolean;
  seoTitle?: boolean;
  metaDescription?: boolean;
  ogImage?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect {
  name?: boolean;
  role?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  email?: boolean;
  resetPasswordToken?: boolean;
  resetPasswordExpiration?: boolean;
  salt?: boolean;
  hash?: boolean;
  loginAttempts?: boolean;
  lockUntil?: boolean;
  sessions?:
    | boolean
    | {
        id?: boolean;
        createdAt?: boolean;
        expiresAt?: boolean;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect {
  key?: boolean;
  data?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect {
  document?: boolean;
  globalSlug?: boolean;
  user?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect {
  user?: boolean;
  key?: boolean;
  value?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect {
  name?: boolean;
  batch?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * Global site configuration — nav, footer, contact, SEO, and announcement banner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Shown at the very top of every page. Leave message blank to hide.
   */
  banner?: {
    enabled?: boolean | null;
    message?: string | null;
    link_label?: string | null;
    link_url?: string | null;
    style?: ('info' | 'success' | 'warning' | 'promo') | null;
  };
  nav?: {
    /**
     * Main links shown in the sidebar / top nav.
     */
    primary_links?:
      | {
          label: string;
          url: string;
          /**
           * e.g. "Zap", "Package", "BookOpen"
           */
          icon?: string | null;
          open_in_new_tab?: boolean | null;
          id?: string | null;
        }[]
      | null;
    cta_label?: string | null;
    cta_url?: string | null;
  };
  footer?: {
    tagline?: string | null;
    link_columns?:
      | {
          heading: string;
          links?:
            | {
                label: string;
                url: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * e.g. "© 2026 Envo. All rights reserved."
     */
    legal_text?: string | null;
    social_links?:
      | {
          platform?: ('linkedin' | 'instagram' | 'facebook' | 'youtube' | 'twitter') | null;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    /**
     * e.g. "Mon–Fri 8am–5pm NZST"
     */
    hours?: string | null;
  };
  seo?: {
    /**
     * Used in title tags: "Product Name | ENVO"
     */
    site_name?: string | null;
    title_separator?: string | null;
    /**
     * Fallback if a page has no specific description.
     */
    default_description?: string | null;
    /**
     * Fallback Open Graph image for social sharing (1200×630px recommended).
     */
    default_og_image?: (number | null) | Media;
    /**
     * e.g. G-XXXXXXXXXX
     */
    google_analytics_id?: string | null;
    /**
     * e.g. GTM-XXXXXXX
     */
    google_tag_manager_id?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for each homepage section. Changes take effect on next publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Small label above the headline.
   */
  hero_eyebrow?: string | null;
  /**
   * Main H1. Use a period at the end.
   */
  hero_headline?: string | null;
  hero_subheading?: string | null;
  /**
   * Path to background video. Leave as-is unless you upload a new one.
   */
  hero_video_url?: string | null;
  /**
   * 3 feature bullets shown under the headline. Leave empty to use defaults.
   */
  hero_features?:
    | {
        label: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  stats_heading?: string | null;
  stats_description?: string | null;
  stats_cta_label?: string | null;
  stats_cta_url?: string | null;
  /**
   * 4 stat cards. Icons are fixed — only text is editable here.
   */
  stats_items?:
    | {
        label: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Testimonial quote. No quotation marks needed — they are added automatically.
   */
  quote_text?: string | null;
  quote_author_role?: string | null;
  quote_author_location?: string | null;
  process_heading?: string | null;
  process_cta_label?: string | null;
  process_cta_url?: string | null;
  /**
   * 4 process steps. Step numbers and icons are fixed.
   */
  process_steps?:
    | {
        name: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  cta_heading?: string | null;
  cta_body?: string | null;
  cta_primary_label?: string | null;
  cta_primary_url?: string | null;
  cta_secondary_label?: string | null;
  cta_secondary_url?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect {
  banner?:
    | boolean
    | {
        enabled?: boolean;
        message?: boolean;
        link_label?: boolean;
        link_url?: boolean;
        style?: boolean;
      };
  nav?:
    | boolean
    | {
        primary_links?:
          | boolean
          | {
              label?: boolean;
              url?: boolean;
              icon?: boolean;
              open_in_new_tab?: boolean;
              id?: boolean;
            };
        cta_label?: boolean;
        cta_url?: boolean;
      };
  footer?:
    | boolean
    | {
        tagline?: boolean;
        link_columns?:
          | boolean
          | {
              heading?: boolean;
              links?:
                | boolean
                | {
                    label?: boolean;
                    url?: boolean;
                    id?: boolean;
                  };
              id?: boolean;
            };
        legal_text?: boolean;
        social_links?:
          | boolean
          | {
              platform?: boolean;
              url?: boolean;
              id?: boolean;
            };
      };
  contact?:
    | boolean
    | {
        email?: boolean;
        phone?: boolean;
        address?: boolean;
        hours?: boolean;
      };
  seo?:
    | boolean
    | {
        site_name?: boolean;
        title_separator?: boolean;
        default_description?: boolean;
        default_og_image?: boolean;
        google_analytics_id?: boolean;
        google_tag_manager_id?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect {
  hero_eyebrow?: boolean;
  hero_headline?: boolean;
  hero_subheading?: boolean;
  hero_video_url?: boolean;
  hero_features?:
    | boolean
    | {
        label?: boolean;
        desc?: boolean;
        id?: boolean;
      };
  stats_heading?: boolean;
  stats_description?: boolean;
  stats_cta_label?: boolean;
  stats_cta_url?: boolean;
  stats_items?:
    | boolean
    | {
        label?: boolean;
        desc?: boolean;
        id?: boolean;
      };
  quote_text?: boolean;
  quote_author_role?: boolean;
  quote_author_location?: boolean;
  process_heading?: boolean;
  process_cta_label?: boolean;
  process_cta_url?: boolean;
  process_steps?:
    | boolean
    | {
        name?: boolean;
        desc?: boolean;
        id?: boolean;
      };
  cta_heading?: boolean;
  cta_body?: boolean;
  cta_primary_label?: boolean;
  cta_primary_url?: boolean;
  cta_secondary_label?: boolean;
  cta_secondary_url?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
