/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `npm run generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    media: Media;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect;
    media: MediaSelect;
    'payload-kv': PayloadKvSelect;
    users: UsersSelect;
    'payload-locked-documents': PayloadLockedDocumentsSelect;
    'payload-preferences': PayloadPreferencesSelect;
    'payload-migrations': PayloadMigrationsSelect;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * ENVO product catalogue. Synced from Akeneo — edit freely. Enable sync_locked to prevent Akeneo from overwriting your changes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Synced from Akeneo. Edit freely.
   */
  name: string;
  /**
   * Short tagline shown under the product name.
   */
  subtitle?: string | null;
  /**
   * One-line summary used in search results and meta tags.
   */
  short_description?: string | null;
  /**
   * Full product description. Accepts HTML. Synced from Akeneo — edit to override.
   */
  description?: string | null;
  /**
   * Show on website.
   */
  enabled?: boolean | null;
  /**
   * Hide without disabling in Akeneo.
   */
  hidden?: boolean | null;
  /**
   * Primary product image. Upload to replace the Akeneo image.
   */
  image?: (number | null) | Media;
  /**
   * Clean product image on white background. Used for category cards.
   */
  clean_image?: (number | null) | Media;
  /**
   * Akeneo S3 image URL — used automatically if no image is uploaded above. Do not edit.
   */
  image_url_fallback?: string | null;
  /**
   * Akeneo S3 clean image URL — fallback if no clean image uploaded. Do not edit.
   */
  clean_image_url_fallback?: string | null;
  /**
   * Link to the spec sheet PDF. Can be an Akeneo URL or any external link.
   */
  spec_sheet_url?: string | null;
  power_w?: number | null;
  output_voltage_v?: number | null;
  input_voltage_min_v?: number | null;
  input_voltage_max_v?: number | null;
  rated_current_a?: number | null;
  number_of_outputs?: number | null;
  operation_mode?: ('cv' | 'cc' | 'cv_cc') | null;
  dimming_control?:
    | ('none' | 'dali' | '0_10v' | 'pwm' | 'triac' | 'casambi' | 'dmx' | 'knx' | 'matter' | 'zigbee')[]
    | null;
  cc_region_min?: number | null;
  cc_region_max?: number | null;
  /**
   * Raw array from Akeneo. e.g. ["push_dim","rf"]
   */
  controller_type?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * e.g. 1ch, rgb, rgbw, cct
   */
  output_channel?: string | null;
  /**
   * e.g. cv, cc, pwm
   */
  output_type?: string | null;
  module_size?: number | null;
  switch_no_module?: number | null;
  /**
   * e.g. push, touch, rotary
   */
  switch_operation_method?: string | null;
  /**
   * e.g. surface, recessed, din_rail, in_wall
   */
  mounting_info?: string | null;
  switch_back_light?: boolean | null;
  /**
   * e.g. white, black, silver
   */
  finish_colour?: string | null;
  /**
   * e.g. aluminum, plastic, steel
   */
  material?: string | null;
  brightness_lm?: number | null;
  efficacy_lm_w?: number | null;
  cct_k?: number | null;
  cri?: number | null;
  beam_angle_deg?: number | null;
  lifetime_hrs?: number | null;
  max_in_series?: number | null;
  led_chip_colour?: ('warm_white' | 'natural_white' | 'cool_white' | 'rgb' | 'rgbw' | 'tunable_white') | null;
  led_pitch?: number | null;
  /**
   * Raw array from Akeneo.
   */
  led_light_power_input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  length_mm?: number | null;
  width_mm?: number | null;
  height_mm?: number | null;
  weight_kg?: number | null;
  waterproof?: ('non_waterproof' | 'ip20' | 'ip44' | 'ip65' | 'ip67' | 'ip68') | null;
  temp_min_c?: number | null;
  temp_max_c?: number | null;
  sensor_type?: ('pir' | 'microwave' | 'daylight' | 'dual') | null;
  /**
   * e.g. pir, microwave, infrared
   */
  technology?: string | null;
  /**
   * e.g. 12m, 6m radius
   */
  maximum_detection_range?: string | null;
  multiway?: boolean | null;
  standards_met?:
    | ('c_ce' | 'c_saa' | 'c_tuv' | 'c_ul' | 'c_rcm' | 'c_fcc' | 'c_rohs' | 'c_enec' | 'c_bis' | 'c_cb' | 'c_lm80')[]
    | null;
  warranty_years?: number | null;
  /**
   * Retail price ex-GST.
   */
  price_nzd?: number | null;
  inventory_type?: ('stocked' | 'on_demand') | null;
  /**
   * Units per carton.
   */
  pack_qty?: number | null;
  shipping_lead_days?: number | null;
  manufacturing_lead_days?: number | null;
  /**
   * Show in featured sections.
   */
  featured?: boolean | null;
  badge?: ('' | 'new' | 'popular' | 'sale' | 'clearance') | null;
  /**
   * Lower = appears first.
   */
  display_order?: number | null;
  /**
   * Short note on the product page. e.g. "Popular for commercial signage."
   */
  marketing_note?: string | null;
  /**
   * Which application pages feature this product.
   */
  applications?:
    | {
        /**
         * e.g. signage, cabinetry, residential, outdoor
         */
        application_slug: string;
        /**
         * Pin to top of this application page.
         */
        pinned?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Manually curated. Leave empty to auto-generate from same series.
   */
  related_skus?:
    | {
        /**
         * e.g. SC-60-24
         */
        sku: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Page title tag. Synced from Akeneo.
   */
  seo_title?: string | null;
  /**
   * Meta description. Synced from Akeneo.
   */
  seo_description?: string | null;
  /**
   * Questions and answers shown on the product page. Synced from Akeneo — edit freely.
   */
  faq?:
    | {
        question: string;
        answer: string;
        category?: ('Specs' | 'Application' | 'Compatibility' | 'Environment' | 'Comparison') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, Akeneo sync will skip this product entirely. Use when you have manually customised this product and do not want it overwritten.
   */
  sync_locked?: boolean | null;
  /**
   * Akeneo SKU — do not edit.
   */
  sku: string;
  family?: string | null;
  series?: string | null;
  brand?: string | null;
  /**
   * Akeneo category codes.
   */
  categories?:
    | {
        code?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Last time this product was updated from Akeneo.
   */
  akeneo_synced_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO. e.g. "SC-100-24 LED Driver front view"
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect {
  name?: boolean;
  subtitle?: boolean;
  short_description?: boolean;
  description?: boolean;
  enabled?: boolean;
  hidden?: boolean;
  image?: boolean;
  clean_image?: boolean;
  image_url_fallback?: boolean;
  clean_image_url_fallback?: boolean;
  spec_sheet_url?: boolean;
  power_w?: boolean;
  output_voltage_v?: boolean;
  input_voltage_min_v?: boolean;
  input_voltage_max_v?: boolean;
  rated_current_a?: boolean;
  number_of_outputs?: boolean;
  operation_mode?: boolean;
  dimming_control?: boolean;
  cc_region_min?: boolean;
  cc_region_max?: boolean;
  controller_type?: boolean;
  output_channel?: boolean;
  output_type?: boolean;
  module_size?: boolean;
  switch_no_module?: boolean;
  switch_operation_method?: boolean;
  mounting_info?: boolean;
  switch_back_light?: boolean;
  finish_colour?: boolean;
  material?: boolean;
  brightness_lm?: boolean;
  efficacy_lm_w?: boolean;
  cct_k?: boolean;
  cri?: boolean;
  beam_angle_deg?: boolean;
  lifetime_hrs?: boolean;
  max_in_series?: boolean;
  led_chip_colour?: boolean;
  led_pitch?: boolean;
  led_light_power_input?: boolean;
  length_mm?: boolean;
  width_mm?: boolean;
  height_mm?: boolean;
  weight_kg?: boolean;
  waterproof?: boolean;
  temp_min_c?: boolean;
  temp_max_c?: boolean;
  sensor_type?: boolean;
  technology?: boolean;
  maximum_detection_range?: boolean;
  multiway?: boolean;
  standards_met?: boolean;
  warranty_years?: boolean;
  price_nzd?: boolean;
  inventory_type?: boolean;
  pack_qty?: boolean;
  shipping_lead_days?: boolean;
  manufacturing_lead_days?: boolean;
  featured?: boolean;
  badge?: boolean;
  display_order?: boolean;
  marketing_note?: boolean;
  applications?:
    | boolean
    | {
        application_slug?: boolean;
        pinned?: boolean;
        id?: boolean;
      };
  related_skus?:
    | boolean
    | {
        sku?: boolean;
        id?: boolean;
      };
  seo_title?: boolean;
  seo_description?: boolean;
  faq?:
    | boolean
    | {
        question?: boolean;
        answer?: boolean;
        category?: boolean;
        id?: boolean;
      };
  sync_locked?: boolean;
  sku?: boolean;
  family?: boolean;
  series?: boolean;
  brand?: boolean;
  categories?:
    | boolean
    | {
        code?: boolean;
        id?: boolean;
      };
  akeneo_synced_at?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect {
  alt?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  url?: boolean;
  thumbnailURL?: boolean;
  filename?: boolean;
  mimeType?: boolean;
  filesize?: boolean;
  width?: boolean;
  height?: boolean;
  focalX?: boolean;
  focalY?: boolean;
  sizes?:
    | boolean
    | {
        thumbnail?:
          | boolean
          | {
              url?: boolean;
              width?: boolean;
              height?: boolean;
              mimeType?: boolean;
              filesize?: boolean;
              filename?: boolean;
            };
        card?:
          | boolean
          | {
              url?: boolean;
              width?: boolean;
              height?: boolean;
              mimeType?: boolean;
              filesize?: boolean;
              filename?: boolean;
            };
        detail?:
          | boolean
          | {
              url?: boolean;
              width?: boolean;
              height?: boolean;
              mimeType?: boolean;
              filesize?: boolean;
              filename?: boolean;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect {
  key?: boolean;
  data?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect {
  updatedAt?: boolean;
  createdAt?: boolean;
  email?: boolean;
  resetPasswordToken?: boolean;
  resetPasswordExpiration?: boolean;
  salt?: boolean;
  hash?: boolean;
  loginAttempts?: boolean;
  lockUntil?: boolean;
  sessions?:
    | boolean
    | {
        id?: boolean;
        createdAt?: boolean;
        expiresAt?: boolean;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect {
  document?: boolean;
  globalSlug?: boolean;
  user?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect {
  user?: boolean;
  key?: boolean;
  value?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect {
  name?: boolean;
  batch?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
