// Auto-generated by Payload — run `npm run generate:importmap` or `next dev` to regenerate.
// Maps any custom admin components imported by collections. Empty when none exist.
export const importMap = {}
