// AUTO-GENERATED by scripts/generate-series-editorial.mts — DO NOT EDIT BY HAND.
// PLACEHOLDER copy ("先占位，之后改"): refine in the POSITIONING map then re-run.
// Editorial here is AI-draft and pending Wei review. See memory
// project_series-template-product-grain.

export type SeriesEditorial = (typeof SERIES_EDITORIAL)[keyof typeof SERIES_EDITORIAL]

export const SERIES_EDITORIAL = {
  "envo_ultraflare": {
    "aiDraft": true,
    "label": "UltraFlare Series",
    "overview": {
      "headline": "Osram inside. Sealed to IP67.",
      "lede": "The premium backlit module for signage that has to look right and survive the weather — genuine Osram emitters in a fully potted IP67 body.",
      "stats": [
        {
          "value": "180 lm",
          "label": "max / module"
        },
        {
          "value": "170°",
          "label": "beam angle"
        },
        {
          "value": "IP67",
          "label": "ingress"
        },
        {
          "value": "3 CCT",
          "label": "colour temps"
        }
      ],
      "features": [
        {
          "title": "Osram emitters",
          "note": "Premium binned chips, lot to lot."
        },
        {
          "title": "Fully potted",
          "note": "IP67 — outdoor & wet-rated."
        },
        {
          "title": "High output",
          "note": "Up to 180 lm per module."
        },
        {
          "title": "12 V DC",
          "note": "4 models, one platform."
        },
        {
          "title": "50,000 h",
          "note": "Rated lifetime."
        },
        {
          "title": "6 marks",
          "note": "BIS · CB · CE · RoHS · TÜV · UL"
        }
      ]
    },
    "solutions": {
      "cards": [
        {
          "title": "Exposed outdoor signage",
          "pick": "highest IP, full brightness"
        },
        {
          "title": "Coastal & wet locations",
          "pick": "fully potted body"
        },
        {
          "title": "Brand-critical retail facades",
          "pick": "Osram colour fidelity"
        },
        {
          "title": "Large illuminated cabinets",
          "pick": "top of the output range"
        }
      ]
    },
    "models": [
      {
        "code": "EV-BLUF01LBY",
        "leds": "Single",
        "powerW": 0.5,
        "lumens": 60,
        "dimsMm": "27.8 × 15.4 × 10.4"
      },
      {
        "code": "EV-BLUF02LBY",
        "leds": "Double",
        "powerW": 1,
        "lumens": 110,
        "dimsMm": "52.8 × 15.4 × 10.4"
      },
      {
        "code": "EV-BLUF03LBY",
        "leds": "Triple",
        "powerW": 1.5,
        "lumens": 165,
        "dimsMm": "77.8 × 15.4 × 10.4"
      },
      {
        "code": "EV-BLUF04LBY",
        "leds": "Quad",
        "powerW": 2,
        "lumens": 180,
        "dimsMm": "47.3 × 40.3 × 10.4"
      }
    ],
    "cctOptions": [
      "WW=3000K",
      "NW=4000K",
      "CW=6500K"
    ],
    "sharedSpecs": {
      "beamDeg": 170,
      "ip": "IP67",
      "voltsDc": 12,
      "lifetimeHrs": 50000,
      "certs": [
        "BIS",
        "CB",
        "CE",
        "RoHS",
        "TÜV",
        "UL"
      ]
    }
  },
  "envo_proglo": {
    "aiDraft": true,
    "label": "ProGlo Series",
    "overview": {
      "headline": "Philips light. Professional finish.",
      "lede": "A professional-grade backlit module built on genuine Philips emitters for signage shops that need consistent colour and a dependable supply.",
      "stats": [
        {
          "value": "180 lm",
          "label": "max / module"
        },
        {
          "value": "170°",
          "label": "beam angle"
        },
        {
          "value": "IP66",
          "label": "ingress"
        },
        {
          "value": "3 CCT",
          "label": "colour temps"
        }
      ],
      "features": [
        {
          "title": "Philips emitters",
          "note": "Trusted brand, stable colour."
        },
        {
          "title": "Even fill",
          "note": "Wide lens, no hotspots."
        },
        {
          "title": "Efficient",
          "note": "Low draw per lumen."
        },
        {
          "title": "12 V DC",
          "note": "4 models, one platform."
        },
        {
          "title": "50,000 h",
          "note": "Rated lifetime."
        },
        {
          "title": "6 marks",
          "note": "BIS · CB · CE · RoHS · TÜV · UL"
        }
      ]
    },
    "solutions": {
      "cards": [
        {
          "title": "Retail channel letters",
          "pick": "clean professional fill"
        },
        {
          "title": "Corporate facades",
          "pick": "consistent Philips colour"
        },
        {
          "title": "Lightbox cabinets",
          "pick": "balanced output"
        },
        {
          "title": "Wayfinding & interior signs",
          "pick": "low-glare even glow"
        }
      ]
    },
    "models": [
      {
        "code": "EV-BLPG01LBY",
        "leds": "Single",
        "powerW": 0.36,
        "lumens": 60,
        "dimsMm": "17.4 × 17.42 × 9.6"
      },
      {
        "code": "EV-BLPG02LBY",
        "leds": "Double",
        "powerW": 0.72,
        "lumens": 110,
        "dimsMm": "52 × 18.5 × 9.6"
      },
      {
        "code": "EV-BLPG03LBY",
        "leds": "Triple",
        "powerW": 1.08,
        "lumens": 165,
        "dimsMm": "78 × 18.5 × 9.6"
      },
      {
        "code": "EV-BLPG04LBY",
        "leds": "Quad",
        "powerW": 1.2,
        "lumens": 180,
        "dimsMm": "42.1 × 42.1 × 9.6"
      }
    ],
    "cctOptions": [
      "WW=3000K",
      "NW=4000K",
      "CW=6500K"
    ],
    "sharedSpecs": {
      "beamDeg": 170,
      "ip": "IP66",
      "voltsDc": 12,
      "lifetimeHrs": 50000,
      "certs": [
        "BIS",
        "CB",
        "CE",
        "RoHS",
        "TÜV",
        "UL"
      ]
    }
  },
  "envo_ecoglo": {
    "aiDraft": true,
    "label": "EcoGlo Series",
    "overview": {
      "headline": "The value backlit module.",
      "lede": "Economical backlit lighting for high-volume signage where cost per letter matters — dependable output without the premium price.",
      "stats": [
        {
          "value": "160 lm",
          "label": "max / module"
        },
        {
          "value": "170°",
          "label": "beam angle"
        },
        {
          "value": "IP65",
          "label": "ingress"
        },
        {
          "value": "3 CCT",
          "label": "colour temps"
        }
      ],
      "features": [
        {
          "title": "Best cost per letter",
          "note": "Built for volume jobs."
        },
        {
          "title": "Proven output",
          "note": "Reliable everyday brightness."
        },
        {
          "title": "Easy install",
          "note": "Daisy-chain, cut to length."
        },
        {
          "title": "12 V DC",
          "note": "4 models, one platform."
        },
        {
          "title": "50,000 h",
          "note": "Rated lifetime."
        },
        {
          "title": "6 marks",
          "note": "BIS · CB · CE · RoHS · TÜV · UL"
        }
      ]
    },
    "solutions": {
      "cards": [
        {
          "title": "High-volume channel letters",
          "pick": "lowest cost per run"
        },
        {
          "title": "Standard lightboxes",
          "pick": "everyday brightness"
        },
        {
          "title": "Promotional & temporary signage",
          "pick": "value first"
        },
        {
          "title": "Interior retail signs",
          "pick": "budget-friendly fill"
        }
      ]
    },
    "models": [
      {
        "code": "EV-BLEG01LBY",
        "leds": "Single",
        "powerW": 0.4,
        "lumens": 40,
        "dimsMm": "36 × 17.5 × 6.2"
      },
      {
        "code": "EV-BLEG02LBY",
        "leds": "Double",
        "powerW": 0.8,
        "lumens": 80,
        "dimsMm": "56 × 17.5 × 6.2"
      },
      {
        "code": "EV-BLEG03LBY",
        "leds": "Triple",
        "powerW": 1.2,
        "lumens": 120,
        "dimsMm": "80 × 17.5 × 6.2"
      },
      {
        "code": "EV-BLEG04LBY",
        "leds": "Quad",
        "powerW": 1.6,
        "lumens": 160,
        "dimsMm": "45 × 43 × 6.2"
      }
    ],
    "cctOptions": [
      "WW=3000K",
      "NW=4000K",
      "CW=7000K"
    ],
    "sharedSpecs": {
      "beamDeg": 170,
      "ip": "IP65",
      "voltsDc": 12,
      "lifetimeHrs": 50000,
      "certs": [
        "BIS",
        "CB",
        "CE",
        "RoHS",
        "TÜV",
        "UL"
      ]
    }
  },
  "envo_optilume": {
    "aiDraft": true,
    "label": "OptiLume Series",
    "overview": {
      "headline": "Efficiency, optimised.",
      "lede": "A 24 V backlit module tuned for efficiency — more sign per watt on long runs and large cabinets.",
      "stats": [
        {
          "value": "200 lm",
          "label": "max / module"
        },
        {
          "value": "170°",
          "label": "beam angle"
        },
        {
          "value": "IP66",
          "label": "ingress"
        },
        {
          "value": "3 CCT",
          "label": "colour temps"
        }
      ],
      "features": [
        {
          "title": "24 V bus",
          "note": "Longer runs, fewer drops."
        },
        {
          "title": "High efficacy",
          "note": "More light per watt."
        },
        {
          "title": "Even fill",
          "note": "Wide lens across the face."
        },
        {
          "title": "24 V DC",
          "note": "2 models, one platform."
        },
        {
          "title": "50,000 h",
          "note": "Rated lifetime."
        },
        {
          "title": "6 marks",
          "note": "BIS · CB · CE · RoHS · TÜV · UL"
        }
      ]
    },
    "solutions": {
      "cards": [
        {
          "title": "Long letter runs",
          "pick": "24 V holds voltage"
        },
        {
          "title": "Large cabinets",
          "pick": "efficient at scale"
        },
        {
          "title": "Energy-conscious projects",
          "pick": "lowest watts per area"
        },
        {
          "title": "Architectural facades",
          "pick": "clean uniform glow"
        }
      ]
    },
    "models": [
      {
        "code": "EV-BLOL02LBY",
        "leds": "Double",
        "powerW": 0.66,
        "lumens": 100,
        "dimsMm": "56 × 10.6 × 10.6"
      },
      {
        "code": "EV-BLOL04LBY",
        "leds": "Quad",
        "powerW": 1.32,
        "lumens": 200,
        "dimsMm": "108 × 10.6 × 10.6"
      }
    ],
    "cctOptions": [
      "WW=3000K",
      "NW=4000K",
      "CW=6500K"
    ],
    "sharedSpecs": {
      "beamDeg": 170,
      "ip": "IP66",
      "voltsDc": 24,
      "lifetimeHrs": 50000,
      "certs": [
        "BIS",
        "CB",
        "CE",
        "RoHS",
        "TÜV",
        "UL"
      ]
    }
  },
  "hydro_lume": {
    "aiDraft": true,
    "label": "HydroLume Series",
    "overview": {
      "headline": "Built for water. Lit by Philips.",
      "lede": "An IP67 24 V backlit module on Philips emitters — engineered for wet, humid and washdown environments where ordinary modules fail.",
      "stats": [
        {
          "value": "252 lm",
          "label": "max / module"
        },
        {
          "value": "180°",
          "label": "beam angle"
        },
        {
          "value": "IP67",
          "label": "ingress"
        },
        {
          "value": "3 CCT",
          "label": "colour temps"
        }
      ],
      "features": [
        {
          "title": "IP67 sealed",
          "note": "Wet & washdown rated."
        },
        {
          "title": "Philips emitters",
          "note": "Stable colour, long life."
        },
        {
          "title": "24 V bus",
          "note": "Long runs without drop-off."
        },
        {
          "title": "24 V DC",
          "note": "3 models, one platform."
        },
        {
          "title": "50,000 h",
          "note": "Rated lifetime."
        }
      ]
    },
    "solutions": {
      "cards": [
        {
          "title": "Wet & washdown signage",
          "pick": "IP67 sealed body"
        },
        {
          "title": "Coastal & marine",
          "pick": "corrosion-resistant build"
        },
        {
          "title": "Pool & leisure venues",
          "pick": "humidity-proof"
        },
        {
          "title": "Outdoor pylon signs",
          "pick": "all-weather rated"
        }
      ]
    },
    "models": [
      {
        "code": "EV-BLHL01SS",
        "leds": "Single",
        "powerW": 0.48,
        "lumens": 82,
        "dimsMm": "42 × 20 × 7"
      },
      {
        "code": "EV-BLHL02SS",
        "leds": "Double",
        "powerW": 0.96,
        "lumens": 164,
        "dimsMm": "56 × 20 × 7"
      },
      {
        "code": "EV-BLHL03SS",
        "leds": "Triple",
        "powerW": 1.44,
        "lumens": 252,
        "dimsMm": "84 × 20 × 7"
      }
    ],
    "cctOptions": [
      "WW=3000K",
      "NW=4000K",
      "CW=6500K"
    ],
    "sharedSpecs": {
      "beamDeg": 180,
      "ip": "IP67",
      "voltsDc": 24,
      "lifetimeHrs": 50000,
      "certs": []
    }
  },
  "envo_chromaflux": {
    "aiDraft": true,
    "label": "ChromaFlux Series",
    "overview": {
      "headline": "One module. Every colour.",
      "lede": "An RGBW backlit module that does full-colour and crisp white from the same unit — for signage and feature lighting that has to change.",
      "stats": [
        {
          "value": "53 lm",
          "label": "max / module"
        },
        {
          "value": "160°",
          "label": "beam angle"
        },
        {
          "value": "IP65",
          "label": "ingress"
        }
      ],
      "features": [
        {
          "title": "RGBW in one",
          "note": "Colour + true white."
        },
        {
          "title": "Addressable-ready",
          "note": "Scenes and effects."
        },
        {
          "title": "Even mix",
          "note": "No colour fringing."
        },
        {
          "title": "12 V DC",
          "note": "2 models, one platform."
        },
        {
          "title": "50,000 h",
          "note": "Rated lifetime."
        },
        {
          "title": "6 marks",
          "note": "BIS · CB · CE · RoHS · TÜV · UL"
        }
      ]
    },
    "solutions": {
      "cards": [
        {
          "title": "Dynamic brand signage",
          "pick": "colour-changing RGBW"
        },
        {
          "title": "Feature & accent lighting",
          "pick": "scene control"
        },
        {
          "title": "Entertainment & hospitality",
          "pick": "full-colour effects"
        },
        {
          "title": "White + colour signs",
          "pick": "one module does both"
        }
      ]
    },
    "models": [
      {
        "code": "EV-BLCF03LBY-RGB",
        "leds": "—",
        "powerW": 0.65,
        "lumens": 33,
        "dimsMm": "87 × 17.5 × 8.4"
      },
      {
        "code": "EV-BLCF03LBY-RGBW",
        "leds": "—",
        "powerW": 0.96,
        "lumens": 53,
        "dimsMm": "87 × 17.5 × 8.4"
      }
    ],
    "cctOptions": [],
    "sharedSpecs": {
      "beamDeg": 160,
      "ip": "IP65",
      "voltsDc": 12,
      "lifetimeHrs": 50000,
      "certs": [
        "BIS",
        "CB",
        "CE",
        "RoHS",
        "TÜV",
        "UL"
      ]
    }
  },
  "envo_edgelume": {
    "aiDraft": true,
    "label": "EdgeLume Series",
    "overview": {
      "headline": "Edge-lit. Slim by design.",
      "lede": "A sidelit module for slim faces and edge-lit cabinets where a backlit module is simply too deep.",
      "stats": [
        {
          "value": "125 lm",
          "label": "max / module"
        },
        {
          "value": "10°",
          "label": "beam angle"
        },
        {
          "value": "IP65",
          "label": "ingress"
        },
        {
          "value": "3 CCT",
          "label": "colour temps"
        }
      ],
      "features": [
        {
          "title": "Sidelit optic",
          "note": "Lights from the edge."
        },
        {
          "title": "Ultra-slim builds",
          "note": "Fits shallow faces."
        },
        {
          "title": "Even edge glow",
          "note": "No bright spots."
        },
        {
          "title": "12 V DC",
          "note": "1 models, one platform."
        },
        {
          "title": "50,000 h",
          "note": "Rated lifetime."
        }
      ]
    },
    "solutions": {
      "cards": [
        {
          "title": "Slim edge-lit signs",
          "pick": "sidelit, shallow depth"
        },
        {
          "title": "Acrylic light panels",
          "pick": "edge injection"
        },
        {
          "title": "Thin lightboxes",
          "pick": "minimal cabinet depth"
        },
        {
          "title": "Decorative trim",
          "pick": "fine edge accent"
        }
      ]
    },
    "models": [
      {
        "code": "EV-SLEL01LBY",
        "leds": "Single",
        "powerW": 1.32,
        "lumens": 125,
        "dimsMm": "43 × 23 × 11.6"
      }
    ],
    "cctOptions": [
      "WW=3000K",
      "NW=4000K",
      "CW=7000K"
    ],
    "sharedSpecs": {
      "beamDeg": 10,
      "ip": "IP65",
      "voltsDc": 12,
      "lifetimeHrs": 50000,
      "certs": []
    }
  },
  "envo_edgeflare": {
    "aiDraft": true,
    "label": "EdgeFlare Series",
    "overview": {
      "headline": "Edge-lit. Turned up.",
      "lede": "A brighter sidelit module for larger edge-lit faces that need more punch than an entry sidelit can give.",
      "stats": [
        {
          "value": "250 lm",
          "label": "max / module"
        },
        {
          "value": "15°",
          "label": "beam angle"
        },
        {
          "value": "IP65",
          "label": "ingress"
        },
        {
          "value": "3 CCT",
          "label": "colour temps"
        }
      ],
      "features": [
        {
          "title": "Brighter sidelit",
          "note": "More output per edge."
        },
        {
          "title": "Larger panels",
          "note": "Drives bigger faces."
        },
        {
          "title": "Even injection",
          "note": "Uniform edge fill."
        },
        {
          "title": "12 V DC",
          "note": "1 models, one platform."
        },
        {
          "title": "50,000 h",
          "note": "Rated lifetime."
        }
      ]
    },
    "solutions": {
      "cards": [
        {
          "title": "Large edge-lit signs",
          "pick": "higher sidelit output"
        },
        {
          "title": "Wide acrylic panels",
          "pick": "reaches across the face"
        },
        {
          "title": "Premium lightboxes",
          "pick": "bright, slim profile"
        },
        {
          "title": "Architectural edge features",
          "pick": "strong even glow"
        }
      ]
    },
    "models": [
      {
        "code": "EV-SLEF01LBY",
        "leds": "Single",
        "powerW": 2.5,
        "lumens": 250,
        "dimsMm": "45 × 32 × 14.8"
      }
    ],
    "cctOptions": [
      "WW=3000K",
      "NW=4000K",
      "CW=7000K"
    ],
    "sharedSpecs": {
      "beamDeg": 15,
      "ip": "IP65",
      "voltsDc": 12,
      "lifetimeHrs": 50000,
      "certs": []
    }
  },
  "envo_edgeblade": {
    "aiDraft": true,
    "label": "EdgeBlade Series",
    "overview": {
      "headline": "High-output edge-lit.",
      "lede": "The high-output sidelit module — maximum brightness from the edge for the most demanding slim faces.",
      "stats": [
        {
          "value": "310 lm",
          "label": "max / module"
        },
        {
          "value": "5°",
          "label": "beam angle"
        },
        {
          "value": "IP65",
          "label": "ingress"
        },
        {
          "value": "3 CCT",
          "label": "colour temps"
        }
      ],
      "features": [
        {
          "title": "Top sidelit output",
          "note": "Max brightness per edge."
        },
        {
          "title": "Big slim faces",
          "note": "Drives the largest panels."
        },
        {
          "title": "Even fill",
          "note": "Uniform across the edge."
        },
        {
          "title": "12 V DC",
          "note": "1 models, one platform."
        },
        {
          "title": "50,000 h",
          "note": "Rated lifetime."
        }
      ]
    },
    "solutions": {
      "cards": [
        {
          "title": "Large slim facades",
          "pick": "highest sidelit output"
        },
        {
          "title": "Premium edge-lit cabinets",
          "pick": "bright, shallow"
        },
        {
          "title": "Backlit-look signs without the depth",
          "pick": "sidelit punch"
        },
        {
          "title": "Feature architectural panels",
          "pick": "strong even edge"
        }
      ]
    },
    "models": [
      {
        "code": "EV-SLEB01LBY",
        "leds": "Single",
        "powerW": 3.5,
        "lumens": 310,
        "dimsMm": "66 × 33 × 18"
      }
    ],
    "cctOptions": [
      "WW=3000K",
      "NW=4000K",
      "CW=7000K"
    ],
    "sharedSpecs": {
      "beamDeg": 5,
      "ip": "IP65",
      "voltsDc": 12,
      "lifetimeHrs": 50000,
      "certs": []
    }
  },
  "edge_blade_2": {
    "aiDraft": true,
    "label": "EdgeBlade2 Series",
    "overview": {
      "headline": "Edge-lit. Sealed and stronger.",
      "lede": "The next EdgeBlade — a 24 V IP67 sidelit module that brings high-output edge lighting outdoors and into wet locations.",
      "stats": [
        {
          "value": "400 lm",
          "label": "max / module"
        },
        {
          "value": "10°",
          "label": "beam angle"
        },
        {
          "value": "IP67",
          "label": "ingress"
        },
        {
          "value": "2 CCT",
          "label": "colour temps"
        }
      ],
      "features": [
        {
          "title": "IP67 sealed",
          "note": "Edge-lit, now outdoor-rated."
        },
        {
          "title": "24 V bus",
          "note": "Longer runs, big panels."
        },
        {
          "title": "High output",
          "note": "Brightest EdgeBlade yet."
        },
        {
          "title": "24 V DC",
          "note": "1 models, one platform."
        },
        {
          "title": "50,000 h",
          "note": "Rated lifetime."
        }
      ]
    },
    "solutions": {
      "cards": [
        {
          "title": "Outdoor edge-lit signs",
          "pick": "IP67 sidelit"
        },
        {
          "title": "Large exterior panels",
          "pick": "24 V long runs"
        },
        {
          "title": "Wet-location slim faces",
          "pick": "sealed sidelit"
        },
        {
          "title": "Premium exterior facades",
          "pick": "high-output edge glow"
        }
      ]
    },
    "models": [
      {
        "code": "EV-SLEB02SS",
        "leds": "Double",
        "powerW": 4,
        "lumens": 400,
        "dimsMm": "97.4 × 30 × 14"
      }
    ],
    "cctOptions": [
      "WW=3000K",
      "CW=6500K"
    ],
    "sharedSpecs": {
      "beamDeg": 10,
      "ip": "IP67",
      "voltsDc": 24,
      "lifetimeHrs": 50000,
      "certs": []
    }
  }
} as const
